"""
scraper.py — Download videos from discovered KukuTV API endpoints.

Reads the API catalog generated by analyze_apis.py, fetches content listings,
resolves video stream URLs, and downloads them locally.
"""

import argparse
import json
import os
import re
import subprocess
import sys
import time
from urllib.parse import urlparse

import httpx
from rich.console import Console
from rich.progress import Progress, SpinnerColumn, BarColumn, TextColumn, DownloadColumn

console = Console()

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CATALOG_DIR = os.path.join(PROJECT_ROOT, "metadata", "api_catalog")
VIDEOS_DIR = os.path.join(PROJECT_ROOT, "videos")
METADATA_DIR = os.path.join(PROJECT_ROOT, "metadata", "content")


class KukuTVScraper:
    """Scrape content from KukuTV using discovered API endpoints."""

    def __init__(self, base_url: str = "", auth_headers: dict | None = None):
        self.base_url = base_url
        self.auth_headers = auth_headers or {}
        self.client = httpx.Client(
            headers={
                "User-Agent": "okhttp/4.12.0",  # Typical Android app UA
                **self.auth_headers,
            },
            timeout=30,
            follow_redirects=True,
        )
        os.makedirs(VIDEOS_DIR, exist_ok=True)
        os.makedirs(METADATA_DIR, exist_ok=True)

    @classmethod
    def from_catalog(cls) -> "KukuTVScraper":
        """Initialize scraper from the API catalog."""
        catalog_path = os.path.join(CATALOG_DIR, "api_catalog.json")
        if not os.path.isfile(catalog_path):
            console.print("[red]API catalog not found. Run analyze_apis.py first.[/red]")
            sys.exit(1)

        with open(catalog_path) as f:
            catalog = json.load(f)

        # Extract base URL and auth from first endpoint
        endpoints = catalog.get("endpoints", {})
        base_url = ""
        auth_headers = {}

        for sig, ep in endpoints.items():
            host = ep.get("host", "")
            if host:
                base_url = f"https://{host}"
            ah = ep.get("auth_headers", {})
            if ah:
                auth_headers.update(ah)
            if base_url and auth_headers:
                break

        console.print(f"[cyan]Base URL:[/cyan] {base_url or 'Not found'}")
        console.print(f"[cyan]Auth headers:[/cyan] {list(auth_headers.keys()) or 'None'}")

        return cls(base_url=base_url, auth_headers=auth_headers)

    def fetch_api(self, path: str, params: dict | None = None) -> dict | list | None:
        """Make an API request and return parsed JSON."""
        url = f"{self.base_url}{path}" if not path.startswith("http") else path
        try:
            resp = self.client.get(url, params=params)
            resp.raise_for_status()
            return resp.json()
        except Exception as e:
            console.print(f"  [red]API error for {url}: {e}[/red]")
            return None

    def download_video_ffmpeg(self, url: str, output_path: str) -> bool:
        """Download video using ffmpeg (handles HLS/m3u8 streams)."""
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        cmd = [
            "ffmpeg", "-y",
            "-i", url,
            "-c", "copy",
            "-bsf:a", "aac_adtstoasc",
            output_path,
        ]
        console.print(f"  [dim]ffmpeg → {output_path}[/dim]")
        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode == 0:
            size_mb = os.path.getsize(output_path) / (1024 * 1024)
            console.print(f"  [green]✓ Downloaded ({size_mb:.1f} MB)[/green]")
            return True
        else:
            console.print(f"  [red]ffmpeg failed: {result.stderr[-200:]}[/red]")
            return False

    def download_video_ytdlp(self, url: str, output_path: str) -> bool:
        """Download video using yt-dlp (robust fallback)."""
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        cmd = [
            "yt-dlp",
            "--no-check-certificate",
            "-o", output_path,
            url,
        ]
        console.print(f"  [dim]yt-dlp → {output_path}[/dim]")
        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode == 0:
            console.print(f"  [green]✓ Downloaded via yt-dlp[/green]")
            return True
        else:
            console.print(f"  [red]yt-dlp failed: {result.stderr[-200:]}[/red]")
            return False

    def download_direct(self, url: str, output_path: str) -> bool:
        """Download a direct MP4/MP3 file via HTTP."""
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        try:
            with self.client.stream("GET", url) as resp:
                resp.raise_for_status()
                total = int(resp.headers.get("content-length", 0))
                with open(output_path, "wb") as f:
                    with Progress(
                        SpinnerColumn(), TextColumn("[progress.description]{task.description}"),
                        BarColumn(), DownloadColumn(),
                    ) as progress:
                        task = progress.add_task(f"Downloading", total=total or None)
                        for chunk in resp.iter_bytes(chunk_size=65536):
                            f.write(chunk)
                            progress.advance(task, len(chunk))
            size_mb = os.path.getsize(output_path) / (1024 * 1024)
            console.print(f"  [green]✓ Downloaded ({size_mb:.1f} MB)[/green]")
            return True
        except Exception as e:
            console.print(f"  [red]Download failed: {e}[/red]")
            return False

    def download_video(self, url: str, output_path: str) -> bool:
        """Smart download — pick the right method based on URL type."""
        url_lower = url.lower()

        if ".m3u8" in url_lower:
            # HLS stream → ffmpeg
            if not output_path.endswith(".mp4"):
                output_path = output_path.rsplit(".", 1)[0] + ".mp4"
            return self.download_video_ffmpeg(url, output_path)
        elif ".mpd" in url_lower:
            # DASH → yt-dlp
            return self.download_video_ytdlp(url, output_path)
        elif any(ext in url_lower for ext in [".mp4", ".mp3", ".aac", ".m4a"]):
            # Direct file
            return self.download_direct(url, output_path)
        else:
            # Try yt-dlp as universal fallback
            return self.download_video_ytdlp(url, output_path)

    def scrape_from_catalog_urls(self):
        """Download all video URLs found in the catalog."""
        video_urls_path = os.path.join(CATALOG_DIR, "video_urls.json")
        if not os.path.isfile(video_urls_path):
            console.print("[yellow]No video_urls.json found. Checking catalog...[/yellow]")
            catalog_path = os.path.join(CATALOG_DIR, "api_catalog.json")
            if os.path.isfile(catalog_path):
                with open(catalog_path) as f:
                    catalog = json.load(f)
                video_urls = catalog.get("video_urls", [])
            else:
                console.print("[red]No catalog found. Run analyze_apis.py first.[/red]")
                return
        else:
            with open(video_urls_path) as f:
                video_urls = json.load(f)

        if not video_urls:
            console.print("[yellow]No video URLs found in catalog.[/yellow]")
            return

        console.print(f"\n[bold]Downloading {len(video_urls)} videos...[/bold]\n")

        success = 0
        for i, entry in enumerate(video_urls):
            url = entry if isinstance(entry, str) else entry.get("url", "")
            if not url:
                continue

            parsed = urlparse(url)
            filename = os.path.basename(parsed.path) or f"video_{i}"
            # Sanitize filename
            filename = re.sub(r'[^\w\-.]', '_', filename)
            if not any(filename.endswith(ext) for ext in [".mp4", ".mp3", ".m4a", ".ts"]):
                filename += ".mp4"

            output_path = os.path.join(VIDEOS_DIR, filename)

            if os.path.isfile(output_path):
                console.print(f"  [dim]Skipping (exists): {filename}[/dim]")
                success += 1
                continue

            console.print(f"\n[cyan][{i + 1}/{len(video_urls)}][/cyan] {url[:100]}")
            if self.download_video(url, output_path):
                success += 1
            time.sleep(1)  # Be polite

        console.print(f"\n[bold green]✓ Downloaded {success}/{len(video_urls)} videos[/bold green]")
        console.print(f"Saved to: {VIDEOS_DIR}")

    def scrape_from_api_endpoints(self):
        """
        Attempt to paginate through discovered API endpoints to find more content.
        This is a template — you'll need to customize paths based on actual API structure.
        """
        catalog_path = os.path.join(CATALOG_DIR, "api_catalog.json")
        if not os.path.isfile(catalog_path):
            return

        with open(catalog_path) as f:
            catalog = json.load(f)

        endpoints = catalog.get("endpoints", {})

        # Look for listing/content endpoints
        listing_endpoints = []
        for sig, ep in endpoints.items():
            path = ep.get("path", "")
            if any(kw in path.lower() for kw in [
                "content", "video", "show", "episode", "series", "category",
                "feed", "home", "discover", "trending", "list"
            ]):
                listing_endpoints.append(ep)

        if not listing_endpoints:
            console.print("[yellow]No listing endpoints found. Use catalog URLs instead.[/yellow]")
            return

        console.print(f"\n[bold]Found {len(listing_endpoints)} listing endpoints to explore[/bold]\n")

        all_video_urls = []
        for ep in listing_endpoints:
            path = ep.get("path", "")
            console.print(f"[cyan]Fetching: {ep.get('method')} {path}[/cyan]")
            data = self.fetch_api(path)
            if data:
                # Save raw response
                safe_name = re.sub(r'[^\w]', '_', path.strip('/'))
                with open(os.path.join(METADATA_DIR, f"{safe_name}.json"), "w") as f:
                    json.dump(data, f, indent=2, default=str)

                # Try to extract video URLs from response (recursive search)
                urls = self._extract_urls(data)
                video_urls = [u for u in urls if any(
                    ext in u.lower() for ext in [".m3u8", ".mp4", ".mpd", ".mp3", ".m4a"]
                )]
                if video_urls:
                    console.print(f"  [green]Found {len(video_urls)} video URLs[/green]")
                    all_video_urls.extend(video_urls)

        if all_video_urls:
            # Deduplicate
            all_video_urls = list(set(all_video_urls))
            console.print(f"\n[bold]Total unique video URLs from APIs: {len(all_video_urls)}[/bold]")

            # Save for download
            urls_path = os.path.join(CATALOG_DIR, "api_video_urls.json")
            with open(urls_path, "w") as f:
                json.dump(all_video_urls, f, indent=2)

            # Download
            for i, url in enumerate(all_video_urls):
                parsed = urlparse(url)
                filename = os.path.basename(parsed.path) or f"api_video_{i}.mp4"
                filename = re.sub(r'[^\w\-.]', '_', filename)
                output_path = os.path.join(VIDEOS_DIR, filename)

                if os.path.isfile(output_path):
                    continue

                console.print(f"\n[cyan][{i + 1}/{len(all_video_urls)}][/cyan] {url[:100]}")
                self.download_video(url, output_path)
                time.sleep(1)

    def _extract_urls(self, data, urls=None) -> list[str]:
        """Recursively extract all URL strings from a nested JSON structure."""
        if urls is None:
            urls = []
        if isinstance(data, str):
            if data.startswith("http://") or data.startswith("https://"):
                urls.append(data)
        elif isinstance(data, dict):
            for v in data.values():
                self._extract_urls(v, urls)
        elif isinstance(data, list):
            for item in data:
                self._extract_urls(item, urls)
        return urls


def main():
    parser = argparse.ArgumentParser(description="Download KukuTV videos")
    parser.add_argument("--mode", choices=["catalog", "api", "both"], default="both",
                        help="catalog=download discovered URLs, api=explore endpoints, both=all")
    parser.add_argument("--url", help="Download a single video URL")
    parser.add_argument("--output", help="Output path for single URL download")
    args = parser.parse_args()

    if args.url:
        scraper = KukuTVScraper()
        output = args.output or os.path.join(VIDEOS_DIR, "single_download.mp4")
        scraper.download_video(args.url, output)
        return

    scraper = KukuTVScraper.from_catalog()

    if args.mode in ("catalog", "both"):
        scraper.scrape_from_catalog_urls()

    if args.mode in ("api", "both"):
        scraper.scrape_from_api_endpoints()


if __name__ == "__main__":
    main()
